basePath: /api
definitions:
  models.AddItemRequest:
    properties:
      category:
        type: string
      price:
        type: number
      product_id:
        type: string
      quantity:
        type: integer
    type: object
  models.AuthRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.Cart:
    properties:
      items:
        items:
          $ref: '#/definitions/models.CartItem'
        type: array
      total:
        type: number
      user_id:
        type: string
    type: object
  models.CartItem:
    properties:
      category:
        type: string
      price:
        type: number
      product_id:
        type: string
      quantity:
        type: integer
    type: object
  models.Good:
    properties:
      category:
        type: string
      color:
        type: string
      image_url:
        type: string
      price:
        type: number
      product_id:
        type: string
      sex:
        type: string
      sizes:
        items:
          type: integer
        type: array
      tag:
        type: string
    type: object
  models.RemoveItemRequest:
    properties:
      product_id:
        type: string
    type: object
  models.UpdateItemRequest:
    properties:
      product_id:
        type: string
      type_operation:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for InternerShop App
  title: MarketPlays API
  version: "1.0"
paths:
  /additem:
    post:
      consumes:
      - application/json
      description: Add item to cart
      operationId: add-item
      parameters:
      - description: item info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.AddItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Add Item
      tags:
      - cart
  /clearcart:
    get:
      description: Clear cart by user id from JWT token
      operationId: clear-cart
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Clear Cart
      tags:
      - cart
  /getcart:
    get:
      description: Return user cart by user_id from JWT token
      operationId: get-cart
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Cart'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get cart
      tags:
      - cart
  /getcatalog:
    get:
      description: Return all goods in catalog
      operationId: get-all-catalog
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/models.Good'
              type: array
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: GetAllCatalog
      tags:
      - catalog
  /image/{productID}:
    get:
      description: Return product image by ID
      operationId: get-image
      parameters:
      - description: productID
        in: path
        name: productid
        required: true
        type: string
      produces:
      - image/png
      responses:
        "200":
          description: Product image
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get image
      tags:
      - catalog
  /login:
    post:
      consumes:
      - application/json
      description: login account
      operationId: login-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Return JWT token
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Validation error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: SignIn
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.AuthRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: SignUp
      tags:
      - auth
  /removeitem:
    post:
      consumes:
      - application/json
      description: Remove item from cart by product_id
      operationId: remove-item
      parameters:
      - description: product id
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.RemoveItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Remove Item
      tags:
      - cart
  /updateitem:
    post:
      consumes:
      - application/json
      description: Update item up or down quantity, 0 - down , >0 - up
      operationId: update-item
      parameters:
      - description: product id
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.UpdateItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Update Item
      tags:
      - cart
securityDefinitions:
  BearerAuth:
    description: 'Enter: "Bearer {token}"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
